---
title: "Game Feedback Analysis"
subtitle: "HolyDead Playtest Survey (2025)"
author: "Dawood Parhiar"
date: "22/04/2025"
output: html_document
---

# Clear Console
cat("\014")

```{r setup, include=FALSE}
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

# Load your dataset
survey_data <- read.csv("data/HolyDead_Production_Feedback.csv", stringsAsFactors = FALSE, fileEncoding = "ISO-8859-1")
```

#1. Structure
```{r}
head(survey_data)
str(survey_data)
```

#2. Enjoyment and Controls
```{r}
summary(select(survey_data, `On.a.scale.of.1.5.how.enjoyable.was.the.game`,
                              `How.responsive.did.the.controls.feel.1.Laggy.5.Very.responsive`))
```

#3. Frequency Tables

```{r}
table(survey_data$Were.the.controls.easy.to.learn.)
table(survey_data$Did.you.encounter.any.bugs.or.glitches.)

```

#4. Visualization 
```{r}
hist(survey_data$`On.a.scale.of.1.5.how.enjoyable.was.the.game`,
     main = "Game Enjoyment Distribution",
     xlab = "Enjoyment Rating (1-5)",
     col = "skyblue")
```